[package]
name = "webhookd"
version = "0.2.1-alpha.0"
authors = ["Jiajie Chen <jiegec@qq.com>"]
edition = "2018"
description = "GitLab/GitHub webhook daemon to run scripts on trigger"
repository = "https://github.com/jiegec/webhookd"
readme = "README.md"
keywords = ["webhook", "gitlab", "github"]
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
actix-web = "2.0"
actix-rt = "1.0"
env_logger = "0.6"
hex = "0.4"
log = "0.4"
ring = "0.16"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3.9"
toml = "0.5"

[package.metadata.deb]
name = "webhookd"
assets = [
        ["target/release/webhookd", "usr/bin/webhookd", "755"],
        ["webhookd.service", "lib/systemd/system/", "644"]
]
section = "web"
